name: Admin Approval

on:
  workflow_run:
    workflows: ["Validate Commit"]
    types:
      - requested

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
    - name: Await admin approval
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.PAT }}
        script: |
          const maxRetries = 5;
          let retryCount = 0;
          let { data: { conclusion, status } } = await github.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          });

          console.log(`Workflow run status: ${status}`);
          console.log(`Workflow run conclusion: ${conclusion}`);

          while (status === 'in_progress' && retryCount < maxRetries) {
            console.log('Workflow is still in progress. Waiting for completion...');
            await new Promise(resolve => setTimeout(resolve, 30000)); // wait for 30 seconds
            const { data: updatedRun } = await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            status = updatedRun.status;
            conclusion = updatedRun.conclusion;
            console.log(`Updated workflow run status: ${status}`);
            console.log(`Updated workflow run conclusion: ${conclusion}`);
            retryCount++;
          }

          if (status !== 'completed' || conclusion !== 'success') {
            throw new Error('Admin approval required because the workflow run did not complete successfully.');
          }