name: Approval Workflow

on:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval
        uses: actions/github-script@v5
        with:
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');
            const context = github.context;

            if (context.event.workflow_run.conclusion !== 'success') {
              core.setFailed('First Workflow did not succeed.');
            }

            core.warning('Waiting for manual approval.');

            // Simulate waiting for approval. In practice, this would be a manual approval step.
            await new Promise(resolve => setTimeout(resolve, 3600000)); // Wait 1 hour

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying the project..."
      # Add other necessary deployment steps here