name: Validate Commit

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate commit
      run: echo "Validating commit..."

    - name: Wait for admin approval
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: admin-approval

  approval:
    runs-on: ubuntu-latest
    needs: validate

    steps:
    - name: Wait for approval
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: { conclusion } } = await github.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          });
          if (conclusion !== 'success') {
            throw new Error('Admin approval required');
          }