# .github/workflows/first-workflow.yml
name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: echo "Building the project..."
      # Add other necessary steps here

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Notify for approval
        run: echo "Please approve the deployment in the second workflow."